name: cerate-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "prefix for repo name"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set for repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo
        run: |
          gh repo create jayun-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
