name: output
on: push

jobs:
  create_output:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.check-output.outputs.test }}
    steps:
      - name: echo output
        id: check-output
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - name: check output
        run: |
          echo ${{ steps.check-output.outputs.test }}

  get_output:
    runs-on: ubuntu-latest
    needs: [create_output]
    steps:
      - name: get output
        run: echo ${{ needs.create_output.outputs.test }}
